### ISSUE TITLE
Homebrew link under Required Software section is not working

### ISSUE THREAD

**Issue by amythetester** [Ada-Developers-Academy/jump-start#101]
When I click on the Homebrew link under Required Software, the link does not take me to the section with the details lower on the page. When I open the link in a new tab it takes me to the top of the page. I can see there it could be anchored in the details for installing Homebrew, but they do not appear to be connected at the moment.

**Comment by CheezItMan** [comment]
Thanks for the message, it seems the link was misspelled (packager manager rather than package manager).  I've put in a PR to fix it.
