### ISSUE TITLE
Hyperlink broken in 'Programming Expressions' section of JumpStart.

### ISSUE THREAD

**Issue by TyrFahey** [Ada-Developers-Academy/jump-start#121]
One of the hyperlinks at the top of the page under the 'Activities' header in the Programming Expressions section is broken:
https://github.com/Ada-Developers-Academy/jump-start/tree/master/learning-to-code/programming-expressions#numbers-problem-assignment

It should be linking to:
https://github.com/Ada-Developers-Academy/jump-start/tree/master/learning-to-code/programming-expressions#numbers-problem-assignment-v2

Or, alternately, the file header itself could be modified to map to (https://github.com/Ada-Developers-Academy/jump-start/tree/master/learning-to-code/programming-expressions#numbers-problem-assignment). Either way, the link defaults to the top of the page.

**Comment by farideh971** [comment]
https://github.com/Ada-Developers-Academy/jump-start/tree/master/learning-to-code/programming-expressions#numbers-problem-assignment
