### ISSUE TITLE
Explain IRB better

### ISSUE THREAD

**Issue by sudocrystal** [Ada-Developers-Academy/jump-start#34]
Flesh out https://github.com/Ada-Developers-Academy/jump-start/blob/master/lessons/06-environment-setup/notes/what-even-is-ruby.md to explain IRB better.

**Comment by sudocrystal** [comment]
Also explain atom/running a program from the terminal better. and why to ditch repl.it

**Comment by atelensky** [comment]
This page really helped me understand how to use atom and run a program from the terminal - https://learnrubythehardway.org/book/ex1.html
