### ISSUE TITLE
Minor issue in Notes: Loops

### ISSUE THREAD

**Issue by olenellina** [Ada-Developers-Academy/jump-start#40]
https://github.com/Ada-Developers-Academy/jump-start/blob/master/lessons/10-iterators/notes/loops.md

Output below should be 0, 1 :)

```
2.times do |i|
  puts i # wheeee remember the slide?
end

output:
1
2
```

**Comment by kariabancroft** [comment]
Thanks! We fixed it

**Comment by olenellina** [comment]
Thank you!
