### ISSUE TITLE
Installfest Update for latest releases

### ISSUE THREAD

**Issue by sudocrystal** [Ada-Developers-Academy/jump-start#54]
Modify Installfest (Lesson 7) to reference "lastest release" on everything, instead of specifics;

OS Version
Ruby Version
RVM
etc

**Comment by CheezItMan** [comment]
I've put in a PR which updates the OS version, should we update to Ruby 2.4.0?

**Comment by sudocrystal** [comment]
I was wondering if we just want to generalize it to say "this is where to find the latest of each of these" essentially. But maybe not. At a minimum we should make sure that whatever we are saying here is the same as what we use in class.

**Comment by sudocrystal** [comment]
Also, you're quick!
