### ISSUE TITLE
L08 Hello World

### ISSUE THREAD

**Issue by emartinez0512** [Ada-Developers-Academy/jump-start#57]
Hello World (ba dum tiss, okay please keep reading lol),

I'm stuck on the "Edit the Ruby File" step, I'm not quite sure how to open my text editor? I attached what my terminal looks like right now. Do I need to create a file in atom? I feel as though I am missing a step...

Thank you!
<img width="567" alt="screen shot 2017-01-27 at 9 16 47 am" src="https://cloud.githubusercontent.com/assets/20617805/22375921/9da1461e-e471-11e6-8396-804c41be3f64.png">

**Comment by susanev** [comment]
Instead of `atom.txt` try `atom hello-world.rb` theres a few other things that might be go wrong so feel free to comment again if you need more help

**Comment by emartinez0512** [comment]
I hadn't installed the shell commands. Thank you, it worked now! @susanev
