### ISSUE TITLE
Markdown question

### ISSUE THREAD

**Issue by emartinez0512** [Ada-Developers-Academy/jump-start#58]
I apologize if this is not an appropriate place to ask, but I am working on writing my resume in markdown and am wondering if there is a way to make a bullet point for design, to go in between text without creating a list? I currently just replaced the bullets with | to compensate.

Any advice or guidance is appreciated!

Thank you!

**Comment by susanev** [comment]
I am not sure what you mean by _go in between text_. I have used the [markdown cheat sheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) by [adam-p](https://github.com/adam-p) in the past, maybe that would be useful to you?

**Comment by emartinez0512** [comment]
Here is an example of what I mean by the bullet in between text. I had a hard time describing it, sorry!

Thank you for the cheat sheet -- I am reviewing it now! Would you suggest adding HTML to my markdown resume?
<img width="192" alt="screen shot 2017-02-05 at 10 52 02 pm" src="https://cloud.githubusercontent.com/assets/20617805/22635082/c1d079d4-ebf5-11e6-910a-f42057e852d7.png">

**Comment by susanev** [comment]
@sudocrystal does Ada have any best practices that they expect applicatants to use in their markdown? If something isn't possible to do in markdown can they use HTML?

**Comment by sudocrystal** [comment]
We don't have a best practices guidelines for markdown currently, and we don't encourage HTML being put into markdown. The idea of markdown is that it is easily readable in plain text as well as markdown, so while inserting HTML is allowed, we don't encourage it.
