### ISSUE TITLE
instructions for ruby install on PC

### ISSUE THREAD

**Issue by sudocrystal** [Ada-Developers-Academy/jump-start#64]
Applicants without a mac aren't able to do a lot of installation pieces. Go through lessons 5+ and see if there's an opportunity to add Windows-based instructions for those materials.

**Comment by shrutivanw** [comment]
Here's what we sent in replies to candidates asking for this information:

The Preparing to Code section does have lessons that are Mac specific environment setup. 
Lesson 3 (Effective Internet Searching) and Lesson 5 (Ada programming languages) are relevant regardless of the use of PC or Mac. So, I'd recommend completing these.

Lesson 7 (Environment Setup) provides Mac specific instructions. I'd recommend installing Google Chrome, Atom and Ruby on PC before proceeding to "Learning to Code" section. Here are some links that may help to get these installed:
- Google Chrome https://www.google.com/chrome/
- Atom https://atom.io/
- Ruby https://www.ruby-lang.org/en/documentation/installation/#rubyinstaller
Once Ruby is installed, irb should be available on the command line.

Also, the optional section of Creating a gist from Atom, may still be useful.

After completing the above, all the lessons in the Learning to Code section will still be useful.

**Comment by shrutivanw** [comment]
Completed.
